version: '3.6'

networks: 
  default:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.16.230.0/24

services:
  registry:
    container_name: docker-registry
    image: registry:latest
    networks:
      default:
        ipv4_address: 172.16.230.10
    ports: 
      - "5050:5000"
    volumes:
      - ./registry/var/lib/registry:/var/lib/registry
  jenkins:
    container_name: jenkins-server
    image: jenkins/jenkins:lts
    networks:
      default:
        ipv4_address: 172.16.230.20
    ports: 
      - "5080:8080"
      - "5085:50000"
    volumes:
      - ./jenkins/var/jenkins_home:/var/jenkins_home
  gitlab:
    container_name: gitlab-server
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.ericcharleslzq.com'
    networks:
      default:
        ipv4_address: 172.16.230.30
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.ericcharleslzq.com'
    ports:
      - '5090:80'
      - '5093:443'
      - '5092:22'
    volumes:
      - './gitlab//etc/gitlab:/etc/gitlab'
      - './gitlab/var/log/gitlab:/var/log/gitlab'
      - './gitlab/var/opt/gitlab:/var/opt/gitlab'
