version: '3.6'

networks: 
  default:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.16.238.0/24

services:
  hub:
    container_name: jetbrains-hub 
    image: jetbrains/hub:2018.2.9774
    networks:
      default:
        ipv4_address: 172.16.238.10
    ports: 
      - "5550:8080"
    volumes:
      - ./opt/hub/data:/opt/hub/data
      - ./opt/hub/conf:/opt/hub/conf
      - ./opt/hub/logs:/opt/hub/logs
      - ./opt/hub/backups:/opt/hub/backups
  team-city:
    container_name: team-city
    image: jetbrains/teamcity-server:latest
    depends_on:
      - hub
    networks:
      default:
        ipv4_address: 172.16.238.11
    ports: 
      - "5551:8111"
    extra_hosts:
      - "jethub.ericcharleslzq.com:172.16.238.10"
      - "teamcity.ericcharleslzq.com:172.16.238.11"
    volumes:
      - ./opt/teamcity/logs:/opt/teamcity/logs
      - ./data/teamcity_server/datadir:/data/teamcity_server/datadir
  upsource:
    container_name: upsource
    image: jetbrains/upsource:2018.1.357
    depends_on:
      - hub
    networks:
      default:
        ipv4_address: 172.16.238.12
    ports: 
      - "5552:8080"
    extra_hosts:
      - "jethub.ericcharleslzq.com:172.16.238.10"
    volumes:
      - ./opt/upsource/data:/opt/upsource/data
      - ./opt/upsource/conf:/opt/upsource/conf
      - ./opt/upsource/logs:/opt/upsource/logs
      - ./opt/upsource/backups:/opt/upsource/backups
  youtrack:
    container_name: youtrack
    image: jetbrains/youtrack:2018.2.42337
    depends_on:
      - hub
    networks:
      default:
        ipv4_address: 172.16.238.13
    ports: 
      - "5553:8080"
    extra_hosts:
      - "jethub.ericcharleslzq.com:172.16.238.10"
    volumes:
      - ./opt/youtrack/data:/opt/youtrack/data
      - ./opt/youtrack/conf:/opt/youtrack/conf
      - ./opt/youtrack/logs:/opt/youtrack/logs
      - ./opt/youtrack/backups:/opt/youtrack/backups
  teamcity-agent:
    image: jetbrains/teamcity-agent:latest
    depends_on:
      - team-city
    environment:
      - SERVER_URL=team-city:8111




  
